### LOGSTASH ELASTICSEARCH CONFIGURATION

cluster.name: es-logstash 

index:
    number_of_shards: 4
    number_of_replicas: 1

transport.tcp.port: 9300
http:
    port: 9200
    max_content_length: 250mb
    cors:
        allow-origin: "/.*/"
        enabled: true

# Must include this binding or ES will only band to localhost, preventing access
network.host: 0.0.0.0
    
# We want there to be n-1 nodes where n is the amount of actual nodes. This means the cluster can run in a degraded
# state without entering recovery mode.
gateway:
    expected_nodes: 2
    
path:
   data: /es-data/data
   work: /es-data/work

discovery:
    zen:
	ping.multicast.enabled: true
        minimum_master_nodes: 1
